# NBBinder configuration file for the notebooks in 
# the repository github/rmsrosa/modcovid19

version: 0.12a

path_to_notes: ./notebooks

contents:
  toc_nb_name: 00.00-Pagina_Inicial.ipynb
  show_index_in_toc: True

header: "[*Notas sobre modelagem da epidemia de Covid-19*](https://github.com/rmsrosa/modcovid19) / [*IM-UFRJ*](https://www.im.ufrj.br)."

navigators:
  core_navigators:
    - 00.00-Pagina_Inicial.ipynb
  show_nb_title_in_nav: True
  show_index_in_nav: False

badges:
  - alt: localslides
    title: Local Slides
    url: ../slides
    extension: .slides.html
    label: local
    message: slides
    color: darkgreen

exports:
  - export_path: slides
    exporter_name: slides
    exporter_args:
      reveal_scroll: True
